diff a/include/linux/Kbuild b/include/linux/Kbuild	(rejected hunks)
@@ -447,3 +447,4 @@ header-y += genlock.h
 header-y += msm_audio_amrwb.h
 header-y += msm_audio_amrwbplus.h
 header-y += coresight-stm.h
+header-y += avtimer.h
