diff a/drivers/platform/msm/Makefile b/drivers/platform/msm/Makefile	(rejected hunks)
@@ -7,3 +7,4 @@ obj-$(CONFIG_SPS) += sps/
 obj-$(CONFIG_QPNP_PWM) += qpnp-pwm.o
 obj-$(CONFIG_QPNP_POWER_ON) += qpnp-power-on.o
 obj-$(CONFIG_QPNP_CLKDIV) += qpnp-clkdiv.o
+obj-$(CONFIG_MSM_AVTIMER) += avtimer.o
\ No newline at end of file
